### ISSUE TITLE
Credentials are wrong

### ISSUE THREAD

**Issue by edouardpoitras** [chrisguindon/eclipsefdn-docker#1]
Your docker-compose.yml file has incorrect default credentials and it won't work on my MySQL instance. The credentials should match my instance:

```
environment:
        MYSQL_ROOT_PASSWORD: k*4sE38d$i6l2D
        MYSQL_PASSWORD: trustmeimaprofessional
        MYSQL_USER: edouardpoitras
        MYSQL_DATABASE: phpapp1
```

You should also consider adding the internet-accessible host information for the MySQL instance, such as mine:

```
MYSQL_HOST: 208.76.122.5
```

This works well for me - see my website: https://epoitras.com

Thank you.
